version: '3'
services:
  app:
    image: nginx
    container_name: ghs1
    volumes:
      - .:/usr/share/nginx/html/
    expose:
      - "80"
    networks:
      - ghs1-network

networks:
   ghs1-network:
      name: ghs1-network
