version: '3'
services:
  app:
    image: nginx
    container_name: site1-app
    volumes:
      - .:/usr/share/nginx/html/
    expose:
      - "80"
    networks:
      - site1-network

networks:
   site1-network:
      name: site1-network